package cn.com.reformer.poi.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.LoginRecord;

import cn.com.reformer.poi.db.LoginRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginRecordDaoConfig;

    private final LoginRecordDao loginRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginRecordDaoConfig = daoConfigMap.get(LoginRecordDao.class).clone();
        loginRecordDaoConfig.initIdentityScope(type);

        loginRecordDao = new LoginRecordDao(loginRecordDaoConfig, this);

        registerDao(LoginRecord.class, loginRecordDao);
    }
    
    public void clear() {
        loginRecordDaoConfig.getIdentityScope().clear();
    }

    public LoginRecordDao getLoginRecordDao() {
        return loginRecordDao;
    }

}
