/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_reformer_pos_jni_RfQRCodePay */

#ifndef _Included_cn_com_reformer_pos_jni_RfQRCodePay
#define _Included_cn_com_reformer_pos_jni_RfQRCodePay
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_com_reformer_pos_jni_RfQRCodePay
 * Method:    get_card
 * Signature: (Ljava/lang/String;)Lcn/com/reformer/pos/jni/RfPayResponse;
 */
JNIEXPORT jstring JNICALL Java_cn_com_reformer_pos_jni_RfQRCodePay_getCard
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
