package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table login_records.
 */
public class LoginRecord {

    private Long id;
    private Integer state;
    private String user;
    private String time;

    public LoginRecord() {
    }

    public LoginRecord(Long id) {
        this.id = id;
    }

    public LoginRecord(Long id, Integer state, String user, String time) {
        this.id = id;
        this.state = state;
        this.user = user;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
